const examType = ["PE", "FE", "PE&TE"];
const departments = [
  "Chinese",
  "Computer Science",
  "Computing Fundamental",
  "English",
  "English Preparation Course",
  "Entrepreneurship Development",
  "Examination",
  "Finance",
  "Graduate",
  "Graphic Design",
  "Hospitality Management",
  "Information Assurance",
  "Information Technology Specialization",
  "International Business",
  "Japanese",
  "Korean",
  "LAB",
  "Management",
  "Mathematics",
  "Multimedia Communication",
  "On the job training",
  "Physical Training",
  "Soft Skill",
  "Software Engineering",
  "Traditional Instrument",
  "Vietnamese",
];

export { examType, departments };
